spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodai_menu_test
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: menu-service-test
      auto-offset-reset: earliest

logging:
  level:
    root: INFO
    com.foodai.menu: DEBUG

