spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/promotion_db_dev

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.foodai.promotion: DEBUG
    org.springframework.data.mongodb: DEBUG

