package com.foodai.user.mapper;

import com.foodai.user.domain.model.*;
import com.foodai.user.dto.request.*;
import com.foodai.user.dto.response.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for UserMapper.
 */
class UserMapperTest {

    private UserMapper userMapper;

    @BeforeEach
    void setUp() {
        userMapper = Mappers.getMapper(UserMapper.class);
    }

    @Nested
    @DisplayName("ToEntity Tests")
    class ToEntityTests {

        @Test
        @DisplayName("Should map CreateUserRequest to User entity")
        void shouldMapCreateUserRequestToUserEntity() {
            // Arrange
            CreateUserRequest request = CreateUserRequest.builder()
                .phone("+919876543210")
                .email("test@example.com")
                .firstName("John")
                .lastName("Doe")
                .displayName("Johnny")
                .build();

            // Act
            User user = userMapper.toEntity(request);

            // Assert
            assertThat(user).isNotNull();
            assertThat(user.getPhone()).isEqualTo("+919876543210");
            assertThat(user.getEmail()).isEqualTo("test@example.com");
            assertThat(user.getFirstName()).isEqualTo("John");
            assertThat(user.getLastName()).isEqualTo("Doe");
            assertThat(user.getDisplayName()).isEqualTo("Johnny");
            assertThat(user.getId()).isNull(); // Should be generated by MongoDB
        }

        @Test
        @DisplayName("Should handle null request")
        void shouldHandleNullRequest() {
            // Act
            User user = userMapper.toEntity((CreateUserRequest) null);

            // Assert
            assertThat(user).isNull();
        }
    }

    @Nested
    @DisplayName("ToResponse Tests")
    class ToResponseTests {

        @Test
        @DisplayName("Should map User entity to UserResponse")
        void shouldMapUserEntityToUserResponse() {
            // Arrange
            User user = User.builder()
                .id("user-123")
                .phone("+919876543210")
                .email("test@example.com")
                .firstName("John")
                .lastName("Doe")
                .displayName("Johnny")
                .status(UserStatus.ACTIVE)
                .phoneVerified(true)
                .emailVerified(false)
                .totalOrders(10)
                .totalSpent(5000.0)
                .createdAt(Instant.now())
                .build();

            // Act
            UserResponse response = userMapper.toResponse(user);

            // Assert
            assertThat(response).isNotNull();
            assertThat(response.getId()).isEqualTo("user-123");
            assertThat(response.getPhone()).isEqualTo("+919876543210");
            assertThat(response.getEmail()).isEqualTo("test@example.com");
            assertThat(response.getFirstName()).isEqualTo("John");
            assertThat(response.getLastName()).isEqualTo("Doe");
            assertThat(response.getDisplayName()).isEqualTo("Johnny");
            assertThat(response.getStatus()).isEqualTo(UserStatus.ACTIVE);
            assertThat(response.isPhoneVerified()).isTrue();
            assertThat(response.isEmailVerified()).isFalse();
            assertThat(response.getTotalOrders()).isEqualTo(10);
        }

        @Test
        @DisplayName("Should compute full name correctly")
        void shouldComputeFullNameCorrectly() {
            // Arrange
            User user = User.builder()
                .id("user-123")
                .firstName("John")
                .lastName("Doe")
                .build();

            // Act
            UserResponse response = userMapper.toResponse(user);

            // Assert
            assertThat(response.getFullName()).isEqualTo("John Doe");
        }

        @Test
        @DisplayName("Should handle null user")
        void shouldHandleNullUser() {
            // Act
            UserResponse response = userMapper.toResponse(null);

            // Assert
            assertThat(response).isNull();
        }
    }

    @Nested
    @DisplayName("UpdateEntityFromRequest Tests")
    class UpdateEntityFromRequestTests {

        @Test
        @DisplayName("Should update entity from UpdateUserRequest")
        void shouldUpdateEntityFromUpdateUserRequest() {
            // Arrange
            User user = User.builder()
                .id("user-123")
                .firstName("John")
                .lastName("Doe")
                .email("old@example.com")
                .build();

            UpdateUserRequest request = UpdateUserRequest.builder()
                .firstName("Jane")
                .lastName("Smith")
                .build();

            // Act
            userMapper.updateEntityFromRequest(user, request);

            // Assert
            assertThat(user.getFirstName()).isEqualTo("Jane");
            assertThat(user.getLastName()).isEqualTo("Smith");
            assertThat(user.getId()).isEqualTo("user-123"); // Should not change
        }

        @Test
        @DisplayName("Should not update null fields")
        void shouldNotUpdateNullFields() {
            // Arrange
            User user = User.builder()
                .id("user-123")
                .firstName("John")
                .lastName("Doe")
                .email("old@example.com")
                .build();

            UpdateUserRequest request = UpdateUserRequest.builder()
                .firstName("Jane")
                // lastName is null
                .build();

            // Act
            userMapper.updateEntityFromRequest(user, request);

            // Assert
            assertThat(user.getFirstName()).isEqualTo("Jane");
            assertThat(user.getLastName()).isEqualTo("Doe"); // Unchanged
        }
    }

    @Nested
    @DisplayName("Address Mapping Tests")
    class AddressMappingTests {

        @Test
        @DisplayName("Should map AddressDTO to AddressVO")
        void shouldMapAddressDTOToAddressVO() {
            // Arrange
            AddressDTO dto = AddressDTO.builder()
                .label("Home")
                .type(AddressType.HOME)
                .street("123 Main St")
                .city("Mumbai")
                .state("Maharashtra")
                .pincode("400001")
                .landmark("Near Central Park")
                .latitude(19.0760)
                .longitude(72.8777)
                .build();

            // Act
            AddressVO vo = userMapper.toAddressVO(dto);

            // Assert
            assertThat(vo).isNotNull();
            assertThat(vo.getLabel()).isEqualTo("Home");
            assertThat(vo.getType()).isEqualTo(AddressType.HOME);
            assertThat(vo.getStreet()).isEqualTo("123 Main St");
            assertThat(vo.getCity()).isEqualTo("Mumbai");
            assertThat(vo.getState()).isEqualTo("Maharashtra");
            assertThat(vo.getPincode()).isEqualTo("400001");
            assertThat(vo.getLatitude()).isEqualTo(19.0760);
        }

        @Test
        @DisplayName("Should map AddressVO to AddressResponse")
        void shouldMapAddressVOToAddressResponse() {
            // Arrange
            AddressVO vo = AddressVO.builder()
                .id("addr-123")
                .label("Home")
                .type(AddressType.HOME)
                .street("123 Main St")
                .city("Mumbai")
                .pincode("400001")
                .build();

            // Act
            AddressResponse response = userMapper.toAddressResponse(vo);

            // Assert
            assertThat(response).isNotNull();
            assertThat(response.getId()).isEqualTo("addr-123");
            assertThat(response.getLabel()).isEqualTo("Home");
            assertThat(response.getType()).isEqualTo(AddressType.HOME);
            assertThat(response.getCity()).isEqualTo("Mumbai");
            assertThat(response.getPincode()).isEqualTo("400001");
        }

        @Test
        @DisplayName("Should map list of AddressVO to list of AddressResponse")
        void shouldMapListOfAddressVOToListOfAddressResponse() {
            // Arrange
            List<AddressVO> voList = List.of(
                AddressVO.builder().id("addr-1").label("Home").build(),
                AddressVO.builder().id("addr-2").label("Work").build()
            );

            // Act
            List<AddressResponse> responseList = userMapper.toAddressResponseList(voList);

            // Assert
            assertThat(responseList).hasSize(2);
            assertThat(responseList.get(0).getLabel()).isEqualTo("Home");
            assertThat(responseList.get(1).getLabel()).isEqualTo("Work");
        }
    }

    @Nested
    @DisplayName("Preferences Mapping Tests")
    class PreferencesMappingTests {

        @Test
        @DisplayName("Should map DietaryPreferencesDTO to DietaryPreferencesVO")
        void shouldMapDietaryPreferencesDTO() {
            // Arrange
            DietaryPreferencesDTO dto = DietaryPreferencesDTO.builder()
                .vegetarian(true)
                .vegan(false)
                .allergies(List.of("peanuts", "shellfish"))
                .build();

            // Act
            DietaryPreferencesVO vo = userMapper.toDietaryPreferencesVO(dto);

            // Assert
            assertThat(vo).isNotNull();
            assertThat(vo.isVegetarian()).isTrue();
            assertThat(vo.isVegan()).isFalse();
            assertThat(vo.getAllergies()).containsExactly("peanuts", "shellfish");
        }

        @Test
        @DisplayName("Should map NotificationPreferencesDTO to NotificationPreferencesVO")
        void shouldMapNotificationPreferencesDTO() {
            // Arrange
            NotificationPreferencesDTO dto = NotificationPreferencesDTO.builder()
                .pushEnabled(true)
                .smsEnabled(false)
                .emailEnabled(true)
                .build();

            // Act
            NotificationPreferencesVO vo = userMapper.toNotificationPreferencesVO(dto);

            // Assert
            assertThat(vo).isNotNull();
            assertThat(vo.isPushEnabled()).isTrue();
            assertThat(vo.isSmsEnabled()).isFalse();
            assertThat(vo.isEmailEnabled()).isTrue();
        }
    }
}

